package com.github.kiulian.downloader.model.subtitles;


import java.util.regex.Pattern;

public class SubtitlesInfo {
    private static final Pattern fmtRegex = Pattern.compile("&fmt=[^&]*");
    private static final Pattern tlangRegex = Pattern.compile("&tlang=[^&]*");

    private final String url;
    private final String language;
    private final boolean isAutoGenerated;

    public SubtitlesInfo(String url, String language, boolean isAutoGenerated) {
        String filteredUrl = fmtRegex.matcher(url).replaceAll(""); // existing format
        filteredUrl = tlangRegex.matcher(filteredUrl).replaceAll(""); // existing translation language
        this.url = filteredUrl;
        this.language = language;
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getUrl() {
        return url;
    }

    public String getLanguage() {
        return language;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public Subtitles getSubtitles() {
        return new Subtitles(url);
    }

}
