package com.github.kiulian.downloader.model.subtitles;

/*-
 * #
 * Java youtube video and audio downloader
 *
 * Copyright (C) 2020 Igor Kiulian
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #
 */

public class SubtitlesInfo {
    private final String url;
    private final String language;
    private final boolean isAutoGenerated;

    public SubtitlesInfo(String url, String language, boolean isAutoGenerated) {
        this.url = url
                .replaceAll("&fmt=[^&]*", "") // existing format
                .replaceAll("&tlang=[^&]*", ""); // existing translation language;
        this.language = language;
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getUrl() {
        return url;
    }

    public String getLanguage() {
        return language;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    public Subtitles getSubtitles() {
        return new Subtitles(url);
    }

}
